apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tennis-res
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/leschada/tennis-res:29062025.3-arm64
        ports:
        - containerPort: 8080